version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - h2-data:/app/data
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:file:/app/data/testdb
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.h2.Driver
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD:
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_H2_CONSOLE_ENABLED: "true"
      SPRING_H2_CONSOLE_PATH: /h2-console

volumes:
  h2-data:
